"""
carteira.py - Gerencia a carteira de investimentos do usuário.

Tabela: carteira
- id: PK auto-increment
- ativo: ticker ou nome (ex: 'BRL=X', 'Itaúsa', 'Tesouro IPCA 2035')
- descricao: descrição libre (ex: 'USD/BRL', 'Ação ordinária', 'Título público indexado')
- direcao: 'long' ou 'short'
- indexador: 'CDI', 'Prefixado', 'IPCA', 'Dólar', 'Bolsa', 'N/A'
- tamanho: valor em R$ (ex: 50000.0)
- data_criacao: timestamp
- ativa: bool (1/0) para soft delete ou inativação
"""

import pandas as pd
from db import engine
from sqlalchemy import text


COLUNAS_CARTEIRA = ['ativo', 'descricao', 'direcao', 'indexador', 'tamanho']


def _primary_key_sql():
    if engine.dialect.name == 'postgresql':
        return 'INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY'
    return 'INTEGER PRIMARY KEY AUTOINCREMENT'


def criar_tabela_carteira():
    """Cria a tabela 'carteira' no banco se não existir."""
    criar_sql = f"""
    CREATE TABLE IF NOT EXISTS carteira (
        id {_primary_key_sql()},
        ativo TEXT NOT NULL,
        descricao TEXT,
        direcao TEXT NOT NULL CHECK(direcao IN ('long', 'short')),
        indexador TEXT DEFAULT 'N/A',
        tamanho REAL NOT NULL DEFAULT 0.0,
        data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        ativa BOOLEAN DEFAULT TRUE
    );
    """
    try:
        with engine.connect() as conn:
            conn.execute(text(criar_sql))
            conn.commit()
        print("[OK] Tabela 'carteira' criada ou já existe.")
    except Exception as e:
        print(f"[ERRO] Falha ao criar tabela: {e}")


def ler_carteira():
    """Lê toda a carteira ativa do banco."""
    try:
        df = pd.read_sql(
            "SELECT id, ativo, descricao, direcao, indexador, tamanho FROM carteira WHERE ativa = TRUE ORDER BY id",
            engine,
        )
        if df.empty:
            return pd.DataFrame(columns=['id', *COLUNAS_CARTEIRA])
        for coluna in COLUNAS_CARTEIRA:
            if coluna not in df.columns:
                df[coluna] = ""
        return df
    except Exception as e:
        print(f"[ERRO] Falha ao ler carteira: {e}")
        return pd.DataFrame(columns=['id', *COLUNAS_CARTEIRA])


def salvar_carteira(df):
    """Sobrescreve a carteira com dados novos."""
    try:
        if df is None:
            df = pd.DataFrame(columns=COLUNAS_CARTEIRA)

        for coluna in COLUNAS_CARTEIRA:
            if coluna not in df.columns:
                df[coluna] = ""

        with engine.connect() as conn:
            conn.execute(text("DELETE FROM carteira WHERE ativa = TRUE"))
            conn.commit()

        if not df.empty:
            df_clean = df[COLUNAS_CARTEIRA].copy()
            df_clean = df_clean.fillna("")
            df_clean['direcao'] = df_clean['direcao'].astype(str).str.lower().str.strip()
            df_clean['direcao'] = df_clean['direcao'].apply(lambda x: x if x in {'long', 'short'} else 'long')
            df_clean['tamanho'] = pd.to_numeric(df_clean['tamanho'], errors='coerce').fillna(0.0)
            df_clean['ativa'] = True
            df_clean.to_sql('carteira', engine, if_exists='append', index=False)

        print(f"[OK] Carteira salva: {0 if df.empty else len(df)} posicoes.")
        return True
    except Exception as e:
        print(f"[ERRO] Falha ao salvar carteira: {e}")
        return False


def gerar_contexto_carteira():
    """Formata a carteira como texto para injetar no contexto da IA."""
    df = ler_carteira()
    if df.empty:
        return "Carteira vazia."

    contexto = "Carteira do usuario:\n"
    total = float(df['tamanho'].fillna(0).sum())

    for _, row in df.iterrows():
        valor = float(row.get('tamanho', 0) or 0)
        pct = (valor / total * 100) if total > 0 else 0
        contexto += f"  - {row.get('ativo', 'N/A')} ({row.get('direcao', 'long')}, {row.get('indexador', 'N/A')}): R$ {valor:,.2f} ({pct:.1f}%)\n"

    contexto += f"\nTotal investido: R$ {total:,.2f}"
    return contexto


if __name__ == "__main__":
    criar_tabela_carteira()
    print(gerar_contexto_carteira())
