"""
investidas.py - Monitora fatos relevantes de empresas (Itausa e similares).

Fonte: CVM Dados Abertos - Formulário de Fatos Relevantes (IAN/FRE)
API: https://dados.cvm.gov.br/dados/ (via arquivo CSV)

Tabela: investidas
- id: PK auto-increment
- cnpj: CNPJ da empresa (ex: '17.197.092/0001-91' Itausa)
- nome_empresa: nome social
- fato_relevante: texto do fato/evento
- link_cvm: link para o documento na CVM
- data_fato: data do fato
- data_arquivamento: data de arquivamento na CVM
- data_coleta: quando foi coletado
"""

import pandas as pd
from db import engine
from sqlalchemy import text


def _primary_key_sql():
    if engine.dialect.name == 'postgresql':
        return 'INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY'
    return 'INTEGER PRIMARY KEY AUTOINCREMENT'


def criar_tabela_investidas():
    """Cria a tabela 'investidas' no banco se não existir."""
    criar_sql = f"""
    CREATE TABLE IF NOT EXISTS investidas (
        id {_primary_key_sql()},
        cnpj TEXT NOT NULL,
        nome_empresa TEXT,
        fato_relevante TEXT,
        link_cvm TEXT,
        data_fato DATE,
        data_arquivamento DATE,
        data_coleta TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        categoria TEXT,
        tipo TEXT,
        UNIQUE(cnpj, data_fato, fato_relevante)
    );
    """
    try:
        with engine.connect() as conn:
            conn.execute(text(criar_sql))
            # ADITIVO: CREATE TABLE IF NOT EXISTS nao acrescenta coluna a uma
            # tabela que ja existe. Sem isto, bancos criados antes destas
            # colunas fariam o INSERT falhar - erro que so' aparece na hora de
            # gravar, nao na de criar.
            for coluna in ("categoria", "tipo"):
                try:
                    conn.execute(text(f"ALTER TABLE investidas ADD COLUMN {coluna} TEXT"))
                    conn.commit()
                except Exception:
                    conn.rollback()   # ja existe

            # A UNIQUE original era (cnpj, data_fato, fato_relevante), desenhada
            # quando a coleta era um placeholder que nunca rodou. Ela NAO
            # corresponde a identidade do dado real: no IPE da CVM, documentos
            # distintos compartilham assunto e data de referencia - os mapas de
            # votacao da AGE e da AGO da mesma data, por exemplo. Medido: 9 de
            # 50 comunicados da Itausa colidiam, e o lote inteiro era rejeitado.
            # A chave natural e' o LINK, que carrega o numero de protocolo.
            try:
                conn.execute(text("ALTER TABLE investidas "
                                  "DROP CONSTRAINT IF EXISTS "
                                  "investidas_cnpj_data_fato_fato_relevante_key"))
                conn.commit()
            except Exception:
                conn.rollback()
            try:
                conn.execute(text("CREATE UNIQUE INDEX IF NOT EXISTS "
                                  "idx_investidas_link ON investidas (link_cvm)"))
                conn.commit()
            except Exception:
                conn.rollback()
            conn.commit()
        print("[OK] Tabela 'investidas' criada ou ja existe.")
    except Exception as e:
        print(f"[ERRO] Falha ao criar tabela: {e}")


def criar_tabela_empresas_interesse():
    """Cria tabela de empresas monitoradas pelo usuário."""
    criar_sql = f"""
    CREATE TABLE IF NOT EXISTS empresas_interesse (
        id {_primary_key_sql()},
        nome_empresa TEXT NOT NULL,
        cnpj TEXT,
        ativa BOOLEAN DEFAULT TRUE,
        UNIQUE(nome_empresa)
    );
    """
    try:
        with engine.connect() as conn:
            conn.execute(text(criar_sql))
            conn.commit()
        print("[OK] Tabela 'empresas_interesse' criada ou ja existe.")
    except Exception as e:
        print(f"[ERRO] Falha ao criar tabela de empresas: {e}")


def listar_empresas_interesse():
    """Retorna empresas monitoradas."""
    try:
        df = pd.read_sql(
            "SELECT id, nome_empresa, cnpj FROM empresas_interesse WHERE ativa = TRUE ORDER BY nome_empresa ASC",
            engine,
        )
        return df
    except Exception as e:
        print(f"[ERRO] Falha ao listar empresas: {e}")
        return pd.DataFrame(columns=['id', 'nome_empresa', 'cnpj'])


def adicionar_empresa_interesse(nome_empresa, cnpj=""):
    """Adiciona ou atualiza empresa à lista de monitoramento."""
    nome_empresa = (nome_empresa or "").strip()
    if not nome_empresa:
        return False

    cnpj = (cnpj or "").strip()
    try:
        with engine.connect() as conn:
            conn.execute(
                text(
                    """
                    INSERT INTO empresas_interesse (nome_empresa, cnpj, ativa)
                    VALUES (:nome_empresa, :cnpj, TRUE)
                    ON CONFLICT(nome_empresa)
                    DO UPDATE SET cnpj = excluded.cnpj, ativa = TRUE
                    """
                ),
                {"nome_empresa": nome_empresa, "cnpj": cnpj},
            )
            conn.commit()
        return True
    except Exception as e:
        print(f"[ERRO] Falha ao adicionar empresa: {e}")
        return False


def remover_empresa_interesse(nome_empresa):
    """Remove empresa da lista de monitoramento."""
    nome_empresa = (nome_empresa or "").strip()
    if not nome_empresa:
        return False
    try:
        with engine.connect() as conn:
            conn.execute(
                text("UPDATE empresas_interesse SET ativa = FALSE WHERE nome_empresa = :nome_empresa"),
                {"nome_empresa": nome_empresa},
            )
            conn.commit()
        return True
    except Exception as e:
        print(f"[ERRO] Falha ao remover empresa: {e}")
        return False


def buscar_fatos_cvm(cnpj_filtro=None):
    """Placeholder para coleta futura de fatos relevantes da CVM."""
    print("[INFO] Funcao buscar_fatos_cvm em desenvolvimento...")
    print("       (Requer autenticacao ou acesso ao arquivo ZIP da CVM)")
    return []


def filtrar_noticias_por_empresa(nome_empresa):
    """Retorna notícias que mencionam a empresa em questão."""
    nome_empresa = (nome_empresa or "").strip()
    if not nome_empresa:
        return pd.DataFrame(columns=['titulo', 'link', 'data', 'categoria'])
    try:
        df = pd.read_sql(
            text(
                """
                SELECT titulo, link, data, categoria
                FROM noticias
                WHERE UPPER(titulo) LIKE UPPER(:padrao)
                ORDER BY data DESC NULLS LAST
                LIMIT 10
                """
            ),
            engine,
            params={"padrao": f"%{nome_empresa}%"},
        )
        return df
    except Exception as e:
        print(f"[ERRO] Falha ao filtrar noticias: {e}")
        return pd.DataFrame(columns=['titulo', 'link', 'data', 'categoria'])


def filtrar_noticias(noticias, termos=None, categoria=None):
    """Filtra um DataFrame de noticias por termos no titulo e/ou categoria.

    `termos` e' uma lista: a noticia entra se o titulo mencionar QUALQUER um
    deles (OU entre termos - voce quer noticias da Petrobras OU da Vale, nao
    das duas ao mesmo tempo). Ja termos e categoria se somam (E): filtrar por
    empresa e por categoria restringe as duas coisas.

    Funcao pura, sem banco: quem chama traz o DataFrame. Isso a torna
    testavel sem depender do estado do banco, e reaproveitavel por qualquer
    tela.

    A busca e' por MENCAO no titulo, sem acento nem caixa - deliberadamente
    simples. Casar entidade de verdade exigiria dicionario de nomes e
    apelidos ("Petrobras", "PETR4", "estatal petrolifera"), que e' outro
    problema; mencao literal e' previsivel e auditavel, e o usuario ve quantas
    sobraram para perceber quando o filtro esta' apertado demais."""
    import unicodedata

    if noticias is None or len(noticias) == 0:
        return noticias

    def _normalizar(texto):
        texto = str(texto or "")
        sem_acento = unicodedata.normalize("NFKD", texto)
        sem_acento = "".join(c for c in sem_acento if not unicodedata.combining(c))
        return sem_acento.upper()

    resultado = noticias
    termos = [t.strip() for t in (termos or []) if str(t).strip()]
    if termos:
        alvos = [_normalizar(t) for t in termos]
        titulos = resultado["titulo"].map(_normalizar)
        mascara = titulos.apply(lambda t: any(a in t for a in alvos))
        resultado = resultado[mascara]

    if categoria:
        resultado = resultado[resultado["categoria"].astype(str) == str(categoria)]

    return resultado


def categorias_disponiveis(noticias):
    """Categorias realmente presentes nas noticias, sem nulos nem vazios.

    Devolve lista vazia quando nada foi classificado - a tela usa isso para
    NAO exibir um seletor de categoria inutil. Hoje e' o caso: a classificacao
    por IA vem falhando (503 da API), e oferecer o filtro sugeriria uma
    capacidade que nao existe."""
    if noticias is None or len(noticias) == 0 or "categoria" not in noticias:
        return []
    valores = noticias["categoria"].dropna().astype(str).str.strip()
    return sorted({v for v in valores if v and v.lower() != "nan"})


def criar_tabela_companhias_cvm():
    """Cadastro de companhias abertas ATIVAS, espelho local do arquivo da CVM.

    Existe para a tela poder oferecer candidatas na hora de vincular uma
    empresa monitorada ao seu CNPJ - a desambiguacao que transforma casamento
    por nome (traicoeiro: "VALE" traz empresas agricolas) em casamento por
    CNPJ (exato)."""
    criar_sql = """
    CREATE TABLE IF NOT EXISTS cvm_companhias (
        cnpj TEXT PRIMARY KEY,
        cnpj_formatado TEXT,
        denom_social TEXT,
        denom_comerc TEXT,
        setor TEXT,
        codigo_cvm TEXT
    );
    """
    try:
        with engine.connect() as conn:
            conn.execute(text(criar_sql))
            conn.commit()
    except Exception as e:
        print(f"[ERRO] Falha ao criar tabela cvm_companhias: {e}")


def gravar_companhias_cvm(companhias):
    """Substitui o espelho local do cadastro (a CVM republica o arquivo inteiro)."""
    criar_tabela_companhias_cvm()
    try:
        companhias.to_sql("cvm_companhias", engine, if_exists="replace", index=False)
        return len(companhias)
    except Exception as e:
        print(f"[ERRO] Falha ao gravar companhias: {e}")
        return 0


def buscar_companhias_cvm(termo):
    """Companhias ativas cujo nome contem o termo - candidatas para vinculo."""
    termo = (termo or "").strip()
    if not termo:
        return pd.DataFrame(columns=["cnpj", "denom_social", "denom_comerc", "setor"])
    try:
        return pd.read_sql(
            text("""
                SELECT cnpj, cnpj_formatado, denom_social, denom_comerc, setor
                FROM cvm_companhias
                WHERE UPPER(denom_social) LIKE UPPER(:p)
                   OR UPPER(COALESCE(denom_comerc, '')) LIKE UPPER(:p)
                ORDER BY denom_social
                LIMIT 25
            """),
            engine, params={"p": f"%{termo}%"},
        )
    except Exception as e:
        print(f"[ERRO] Falha ao buscar companhias: {e}")
        return pd.DataFrame(columns=["cnpj", "denom_social", "denom_comerc", "setor"])


def cnpjs_monitorados():
    """CNPJs (so' digitos) das empresas monitoradas que ja tem vinculo.

    Empresa cadastrada sem CNPJ fica de fora de proposito: adivinhar o vinculo
    por nome traria a empresa errada ("Itau" casa com "Companhia Itaunense"),
    e coletar comunicado da empresa errada e' pior que nao coletar."""
    try:
        df = pd.read_sql("SELECT cnpj FROM empresas_interesse WHERE ativa = TRUE", engine)
    except Exception:
        return []
    saida = []
    for valor in df.get("cnpj", []):
        digitos = "".join(c for c in str(valor or "") if c.isdigit())
        if len(digitos) == 14:
            saida.append(digitos)
    return sorted(set(saida))


def empresas_sem_vinculo():
    """Empresas monitoradas que ainda nao tem CNPJ valido vinculado.

    A tela usa isto para mostrar o que esta' pendente, em vez de simplesmente
    nao trazer comunicado nenhum e deixar o usuario sem saber por que."""
    try:
        df = pd.read_sql("SELECT nome_empresa, cnpj FROM empresas_interesse WHERE ativa = TRUE", engine)
    except Exception:
        return []
    pendentes = []
    for _, linha in df.iterrows():
        digitos = "".join(c for c in str(linha.get("cnpj") or "") if c.isdigit())
        if len(digitos) != 14:
            pendentes.append(str(linha.get("nome_empresa") or ""))
    return [p for p in pendentes if p]


def gravar_comunicados(comunicados):
    """Grava os comunicados novos em `investidas` (idempotente pelo protocolo).

    Devolve quantos entraram. A CVM republica o arquivo do ano inteiro a cada
    coleta, entao a maioria ja estara' no banco - so' o que e' novo importa."""
    if comunicados is None or len(comunicados) == 0:
        return 0
    criar_tabela_investidas()
    linhas = pd.DataFrame({
        "cnpj": comunicados["CNPJ_Companhia"],
        "nome_empresa": comunicados["Nome_Companhia"],
        "fato_relevante": comunicados["Assunto"],
        "link_cvm": comunicados["Link_Download"],
        "data_fato": pd.to_datetime(comunicados["Data_Referencia"], errors="coerce"),
        "data_arquivamento": pd.to_datetime(comunicados["Data_Entrega"], errors="coerce"),
        "categoria": comunicados["Categoria"],
        "tipo": comunicados.get("Tipo"),
    })
    try:
        existentes = pd.read_sql("SELECT link_cvm FROM investidas", engine)
        ja_temos = set(existentes["link_cvm"].dropna())
    except Exception:
        ja_temos = set()
    novos = linhas[~linhas["link_cvm"].isin(ja_temos)]
    if novos.empty:
        return 0
    try:
        novos.to_sql("investidas", engine, if_exists="append", index=False)
        return len(novos)
    except Exception as e:
        print(f"[ERRO] Falha ao gravar comunicados: {e}")
        return 0


def ler_comunicados(cnpj=None, categoria=None):
    """Comunicados gravados, mais recentes primeiro."""
    consulta = "SELECT * FROM investidas"
    condicoes, params = [], {}
    if cnpj:
        condicoes.append("REPLACE(REPLACE(REPLACE(cnpj,'.',''),'/',''),'-','') = :cnpj")
        params["cnpj"] = "".join(c for c in str(cnpj) if c.isdigit())
    if categoria:
        condicoes.append("categoria = :cat")
        params["cat"] = categoria
    if condicoes:
        consulta += " WHERE " + " AND ".join(condicoes)
    consulta += " ORDER BY data_arquivamento DESC NULLS LAST LIMIT 200"
    try:
        return pd.read_sql(text(consulta), engine, params=params)
    except Exception as e:
        print(f"[ERRO] Falha ao ler comunicados: {e}")
        return pd.DataFrame()


def gerar_alerta_investidas(nome_empresa):
    """Gera texto de alerta se houver notícias ou fatos da empresa."""
    noticias = filtrar_noticias_por_empresa(nome_empresa)
    if noticias.empty:
        return None

    alerta = f"Noticias sobre {nome_empresa}:\n"
    for _, row in noticias.iterrows():
        alerta += f"  - {row['titulo']} ({row['categoria']}) — {row['data']}\n"
    return alerta


if __name__ == "__main__":
    # Auto-testes das funcoes PURAS primeiro: nao tocam banco, entao rodam
    # sempre, mesmo sem conexao.
    import pandas as _pd

    amostra = _pd.DataFrame([
        {"titulo": "Petrobras anuncia dividendo extraordinario", "categoria": "Bolsa"},
        {"titulo": "Copom eleva Selic para 15%", "categoria": "Juros"},
        {"titulo": "Franca nao teme Espanha no jogo de hoje", "categoria": None},
        {"titulo": "ITAUSA divulga resultado do trimestre", "categoria": ""},
    ])

    # Caso 1: filtra por mencao no titulo, ignorando caixa e acento
    assert len(filtrar_noticias(amostra, termos=["petrobras"])) == 1
    assert len(filtrar_noticias(amostra, termos=["FRANCA"])) == 1   # acento no titulo
    assert len(filtrar_noticias(amostra, termos=["itausa"])) == 1   # caixa diferente
    print("[OK] Caso 1: filtro por mencao ignora caixa e acento.")

    # Caso 2: varios termos sao OU entre si - voce quer noticias da Petrobras
    # OU da Itausa, nao as que citam as duas ao mesmo tempo.
    assert len(filtrar_noticias(amostra, termos=["petrobras", "itausa"])) == 2
    print("[OK] Caso 2: termos multiplos se combinam por OU.")

    # Caso 3: termo e categoria se somam (E), restringindo os dois eixos
    assert len(filtrar_noticias(amostra, termos=["petrobras"], categoria="Bolsa")) == 1
    assert len(filtrar_noticias(amostra, termos=["petrobras"], categoria="Juros")) == 0
    print("[OK] Caso 3: termo e categoria se somam por E.")

    # Caso 4: sem filtro nenhum devolve tudo - nao esconde noticia por engano
    assert len(filtrar_noticias(amostra)) == len(amostra)
    assert len(filtrar_noticias(amostra, termos=[])) == len(amostra)
    assert len(filtrar_noticias(amostra, termos=["   "])) == len(amostra)
    print("[OK] Caso 4: sem filtro (ou filtro vazio) devolve tudo.")

    # Caso 5: categorias_disponiveis ignora nulo, vazio e a string "nan".
    # E' o que faz a tela ESCONDER o seletor quando nada foi classificado, em
    # vez de oferecer um filtro inutil.
    assert categorias_disponiveis(amostra) == ["Bolsa", "Juros"]
    sem_classificacao = _pd.DataFrame([{"titulo": "x", "categoria": None},
                                       {"titulo": "y", "categoria": "nan"}])
    assert categorias_disponiveis(sem_classificacao) == []
    print("[OK] Caso 5: categorias_disponiveis ignora nulo, vazio e 'nan'.")

    print("\nTodos os casos passaram.\n")

    # A partir daqui, toca o banco real.
    criar_tabela_investidas()
    criar_tabela_empresas_interesse()
    print("\n=== Teste de monitoramento ===")
    adicionar_empresa_interesse("Itausa", "17.197.092/0001-91")
    noticias = filtrar_noticias_por_empresa("Itausa")
    print(f"Encontradas {len(noticias)} noticias")
    if not noticias.empty:
        print(noticias.head())
