"""
investidas.py - Monitora fatos relevantes de empresas (Itausa e similares).

Fonte: CVM Dados Abertos - Formulário de Fatos Relevantes (IAN/FRE)
API: https://dados.cvm.gov.br/dados/ (via arquivo CSV)

Tabela: investidas
- id: PK auto-increment
- cnpj: CNPJ da empresa (ex: '17.197.092/0001-91' Itausa)
- nome_empresa: nome social
- fato_relevante: texto do fato/evento
- link_cvm: link para o documento na CVM
- data_fato: data do fato
- data_arquivamento: data de arquivamento na CVM
- data_coleta: quando foi coletado
"""

import pandas as pd
from db import engine
from sqlalchemy import text


def _primary_key_sql():
    if engine.dialect.name == 'postgresql':
        return 'INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY'
    return 'INTEGER PRIMARY KEY AUTOINCREMENT'


def criar_tabela_investidas():
    """Cria a tabela 'investidas' no banco se não existir."""
    criar_sql = f"""
    CREATE TABLE IF NOT EXISTS investidas (
        id {_primary_key_sql()},
        cnpj TEXT NOT NULL,
        nome_empresa TEXT,
        fato_relevante TEXT,
        link_cvm TEXT,
        data_fato DATE,
        data_arquivamento DATE,
        data_coleta TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(cnpj, data_fato, fato_relevante)
    );
    """
    try:
        with engine.connect() as conn:
            conn.execute(text(criar_sql))
            conn.commit()
        print("[OK] Tabela 'investidas' criada ou ja existe.")
    except Exception as e:
        print(f"[ERRO] Falha ao criar tabela: {e}")


def criar_tabela_empresas_interesse():
    """Cria tabela de empresas monitoradas pelo usuário."""
    criar_sql = f"""
    CREATE TABLE IF NOT EXISTS empresas_interesse (
        id {_primary_key_sql()},
        nome_empresa TEXT NOT NULL,
        cnpj TEXT,
        ativa BOOLEAN DEFAULT TRUE,
        UNIQUE(nome_empresa)
    );
    """
    try:
        with engine.connect() as conn:
            conn.execute(text(criar_sql))
            conn.commit()
        print("[OK] Tabela 'empresas_interesse' criada ou ja existe.")
    except Exception as e:
        print(f"[ERRO] Falha ao criar tabela de empresas: {e}")


def listar_empresas_interesse():
    """Retorna empresas monitoradas."""
    try:
        df = pd.read_sql(
            "SELECT id, nome_empresa, cnpj FROM empresas_interesse WHERE ativa = TRUE ORDER BY nome_empresa ASC",
            engine,
        )
        return df
    except Exception as e:
        print(f"[ERRO] Falha ao listar empresas: {e}")
        return pd.DataFrame(columns=['id', 'nome_empresa', 'cnpj'])


def adicionar_empresa_interesse(nome_empresa, cnpj=""):
    """Adiciona ou atualiza empresa à lista de monitoramento."""
    nome_empresa = (nome_empresa or "").strip()
    if not nome_empresa:
        return False

    cnpj = (cnpj or "").strip()
    try:
        with engine.connect() as conn:
            conn.execute(
                text(
                    """
                    INSERT INTO empresas_interesse (nome_empresa, cnpj, ativa)
                    VALUES (:nome_empresa, :cnpj, TRUE)
                    ON CONFLICT(nome_empresa)
                    DO UPDATE SET cnpj = excluded.cnpj, ativa = TRUE
                    """
                ),
                {"nome_empresa": nome_empresa, "cnpj": cnpj},
            )
            conn.commit()
        return True
    except Exception as e:
        print(f"[ERRO] Falha ao adicionar empresa: {e}")
        return False


def remover_empresa_interesse(nome_empresa):
    """Remove empresa da lista de monitoramento."""
    nome_empresa = (nome_empresa or "").strip()
    if not nome_empresa:
        return False
    try:
        with engine.connect() as conn:
            conn.execute(
                text("UPDATE empresas_interesse SET ativa = FALSE WHERE nome_empresa = :nome_empresa"),
                {"nome_empresa": nome_empresa},
            )
            conn.commit()
        return True
    except Exception as e:
        print(f"[ERRO] Falha ao remover empresa: {e}")
        return False


def buscar_fatos_cvm(cnpj_filtro=None):
    """Placeholder para coleta futura de fatos relevantes da CVM."""
    print("[INFO] Funcao buscar_fatos_cvm em desenvolvimento...")
    print("       (Requer autenticacao ou acesso ao arquivo ZIP da CVM)")
    return []


def filtrar_noticias_por_empresa(nome_empresa):
    """Retorna notícias que mencionam a empresa em questão."""
    nome_empresa = (nome_empresa or "").strip()
    if not nome_empresa:
        return pd.DataFrame(columns=['titulo', 'link', 'data', 'categoria'])
    try:
        df = pd.read_sql(
            text(
                """
                SELECT titulo, link, data, categoria
                FROM noticias
                WHERE UPPER(titulo) LIKE UPPER(:padrao)
                ORDER BY data DESC NULLS LAST
                LIMIT 10
                """
            ),
            engine,
            params={"padrao": f"%{nome_empresa}%"},
        )
        return df
    except Exception as e:
        print(f"[ERRO] Falha ao filtrar noticias: {e}")
        return pd.DataFrame(columns=['titulo', 'link', 'data', 'categoria'])


def filtrar_noticias(noticias, termos=None, categoria=None):
    """Filtra um DataFrame de noticias por termos no titulo e/ou categoria.

    `termos` e' uma lista: a noticia entra se o titulo mencionar QUALQUER um
    deles (OU entre termos - voce quer noticias da Petrobras OU da Vale, nao
    das duas ao mesmo tempo). Ja termos e categoria se somam (E): filtrar por
    empresa e por categoria restringe as duas coisas.

    Funcao pura, sem banco: quem chama traz o DataFrame. Isso a torna
    testavel sem depender do estado do banco, e reaproveitavel por qualquer
    tela.

    A busca e' por MENCAO no titulo, sem acento nem caixa - deliberadamente
    simples. Casar entidade de verdade exigiria dicionario de nomes e
    apelidos ("Petrobras", "PETR4", "estatal petrolifera"), que e' outro
    problema; mencao literal e' previsivel e auditavel, e o usuario ve quantas
    sobraram para perceber quando o filtro esta' apertado demais."""
    import unicodedata

    if noticias is None or len(noticias) == 0:
        return noticias

    def _normalizar(texto):
        texto = str(texto or "")
        sem_acento = unicodedata.normalize("NFKD", texto)
        sem_acento = "".join(c for c in sem_acento if not unicodedata.combining(c))
        return sem_acento.upper()

    resultado = noticias
    termos = [t.strip() for t in (termos or []) if str(t).strip()]
    if termos:
        alvos = [_normalizar(t) for t in termos]
        titulos = resultado["titulo"].map(_normalizar)
        mascara = titulos.apply(lambda t: any(a in t for a in alvos))
        resultado = resultado[mascara]

    if categoria:
        resultado = resultado[resultado["categoria"].astype(str) == str(categoria)]

    return resultado


def categorias_disponiveis(noticias):
    """Categorias realmente presentes nas noticias, sem nulos nem vazios.

    Devolve lista vazia quando nada foi classificado - a tela usa isso para
    NAO exibir um seletor de categoria inutil. Hoje e' o caso: a classificacao
    por IA vem falhando (503 da API), e oferecer o filtro sugeriria uma
    capacidade que nao existe."""
    if noticias is None or len(noticias) == 0 or "categoria" not in noticias:
        return []
    valores = noticias["categoria"].dropna().astype(str).str.strip()
    return sorted({v for v in valores if v and v.lower() != "nan"})


def gerar_alerta_investidas(nome_empresa):
    """Gera texto de alerta se houver notícias ou fatos da empresa."""
    noticias = filtrar_noticias_por_empresa(nome_empresa)
    if noticias.empty:
        return None

    alerta = f"Noticias sobre {nome_empresa}:\n"
    for _, row in noticias.iterrows():
        alerta += f"  - {row['titulo']} ({row['categoria']}) — {row['data']}\n"
    return alerta


if __name__ == "__main__":
    # Auto-testes das funcoes PURAS primeiro: nao tocam banco, entao rodam
    # sempre, mesmo sem conexao.
    import pandas as _pd

    amostra = _pd.DataFrame([
        {"titulo": "Petrobras anuncia dividendo extraordinario", "categoria": "Bolsa"},
        {"titulo": "Copom eleva Selic para 15%", "categoria": "Juros"},
        {"titulo": "Franca nao teme Espanha no jogo de hoje", "categoria": None},
        {"titulo": "ITAUSA divulga resultado do trimestre", "categoria": ""},
    ])

    # Caso 1: filtra por mencao no titulo, ignorando caixa e acento
    assert len(filtrar_noticias(amostra, termos=["petrobras"])) == 1
    assert len(filtrar_noticias(amostra, termos=["FRANCA"])) == 1   # acento no titulo
    assert len(filtrar_noticias(amostra, termos=["itausa"])) == 1   # caixa diferente
    print("[OK] Caso 1: filtro por mencao ignora caixa e acento.")

    # Caso 2: varios termos sao OU entre si - voce quer noticias da Petrobras
    # OU da Itausa, nao as que citam as duas ao mesmo tempo.
    assert len(filtrar_noticias(amostra, termos=["petrobras", "itausa"])) == 2
    print("[OK] Caso 2: termos multiplos se combinam por OU.")

    # Caso 3: termo e categoria se somam (E), restringindo os dois eixos
    assert len(filtrar_noticias(amostra, termos=["petrobras"], categoria="Bolsa")) == 1
    assert len(filtrar_noticias(amostra, termos=["petrobras"], categoria="Juros")) == 0
    print("[OK] Caso 3: termo e categoria se somam por E.")

    # Caso 4: sem filtro nenhum devolve tudo - nao esconde noticia por engano
    assert len(filtrar_noticias(amostra)) == len(amostra)
    assert len(filtrar_noticias(amostra, termos=[])) == len(amostra)
    assert len(filtrar_noticias(amostra, termos=["   "])) == len(amostra)
    print("[OK] Caso 4: sem filtro (ou filtro vazio) devolve tudo.")

    # Caso 5: categorias_disponiveis ignora nulo, vazio e a string "nan".
    # E' o que faz a tela ESCONDER o seletor quando nada foi classificado, em
    # vez de oferecer um filtro inutil.
    assert categorias_disponiveis(amostra) == ["Bolsa", "Juros"]
    sem_classificacao = _pd.DataFrame([{"titulo": "x", "categoria": None},
                                       {"titulo": "y", "categoria": "nan"}])
    assert categorias_disponiveis(sem_classificacao) == []
    print("[OK] Caso 5: categorias_disponiveis ignora nulo, vazio e 'nan'.")

    print("\nTodos os casos passaram.\n")

    # A partir daqui, toca o banco real.
    criar_tabela_investidas()
    criar_tabela_empresas_interesse()
    print("\n=== Teste de monitoramento ===")
    adicionar_empresa_interesse("Itausa", "17.197.092/0001-91")
    noticias = filtrar_noticias_por_empresa("Itausa")
    print(f"Encontradas {len(noticias)} noticias")
    if not noticias.empty:
        print(noticias.head())
