"""
investidas.py - Monitora fatos relevantes de empresas (Itausa e similares).

Fonte: CVM Dados Abertos - Formulário de Fatos Relevantes (IAN/FRE)
API: https://dados.cvm.gov.br/dados/ (via arquivo CSV)

Tabela: investidas
- id: PK auto-increment
- cnpj: CNPJ da empresa (ex: '17.197.092/0001-91' Itausa)
- nome_empresa: nome social
- fato_relevante: texto do fato/evento
- link_cvm: link para o documento na CVM
- data_fato: data do fato
- data_arquivamento: data de arquivamento na CVM
- data_coleta: quando foi coletado
"""

import pandas as pd
from db import engine
from sqlalchemy import text


def _primary_key_sql():
    if engine.dialect.name == 'postgresql':
        return 'INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY'
    return 'INTEGER PRIMARY KEY AUTOINCREMENT'


def criar_tabela_investidas():
    """Cria a tabela 'investidas' no banco se não existir."""
    criar_sql = f"""
    CREATE TABLE IF NOT EXISTS investidas (
        id {_primary_key_sql()},
        cnpj TEXT NOT NULL,
        nome_empresa TEXT,
        fato_relevante TEXT,
        link_cvm TEXT,
        data_fato DATE,
        data_arquivamento DATE,
        data_coleta TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UNIQUE(cnpj, data_fato, fato_relevante)
    );
    """
    try:
        with engine.connect() as conn:
            conn.execute(text(criar_sql))
            conn.commit()
        print("[OK] Tabela 'investidas' criada ou ja existe.")
    except Exception as e:
        print(f"[ERRO] Falha ao criar tabela: {e}")


def criar_tabela_empresas_interesse():
    """Cria tabela de empresas monitoradas pelo usuário."""
    criar_sql = f"""
    CREATE TABLE IF NOT EXISTS empresas_interesse (
        id {_primary_key_sql()},
        nome_empresa TEXT NOT NULL,
        cnpj TEXT,
        ativa BOOLEAN DEFAULT TRUE,
        UNIQUE(nome_empresa)
    );
    """
    try:
        with engine.connect() as conn:
            conn.execute(text(criar_sql))
            conn.commit()
        print("[OK] Tabela 'empresas_interesse' criada ou ja existe.")
    except Exception as e:
        print(f"[ERRO] Falha ao criar tabela de empresas: {e}")


def listar_empresas_interesse():
    """Retorna empresas monitoradas."""
    try:
        df = pd.read_sql(
            "SELECT id, nome_empresa, cnpj FROM empresas_interesse WHERE ativa = TRUE ORDER BY nome_empresa ASC",
            engine,
        )
        return df
    except Exception as e:
        print(f"[ERRO] Falha ao listar empresas: {e}")
        return pd.DataFrame(columns=['id', 'nome_empresa', 'cnpj'])


def adicionar_empresa_interesse(nome_empresa, cnpj=""):
    """Adiciona ou atualiza empresa à lista de monitoramento."""
    nome_empresa = (nome_empresa or "").strip()
    if not nome_empresa:
        return False

    cnpj = (cnpj or "").strip()
    try:
        with engine.connect() as conn:
            conn.execute(
                text(
                    """
                    INSERT INTO empresas_interesse (nome_empresa, cnpj, ativa)
                    VALUES (:nome_empresa, :cnpj, TRUE)
                    ON CONFLICT(nome_empresa)
                    DO UPDATE SET cnpj = excluded.cnpj, ativa = TRUE
                    """
                ),
                {"nome_empresa": nome_empresa, "cnpj": cnpj},
            )
            conn.commit()
        return True
    except Exception as e:
        print(f"[ERRO] Falha ao adicionar empresa: {e}")
        return False


def remover_empresa_interesse(nome_empresa):
    """Remove empresa da lista de monitoramento."""
    nome_empresa = (nome_empresa or "").strip()
    if not nome_empresa:
        return False
    try:
        with engine.connect() as conn:
            conn.execute(
                text("UPDATE empresas_interesse SET ativa = FALSE WHERE nome_empresa = :nome_empresa"),
                {"nome_empresa": nome_empresa},
            )
            conn.commit()
        return True
    except Exception as e:
        print(f"[ERRO] Falha ao remover empresa: {e}")
        return False


def buscar_fatos_cvm(cnpj_filtro=None):
    """Placeholder para coleta futura de fatos relevantes da CVM."""
    print("[INFO] Funcao buscar_fatos_cvm em desenvolvimento...")
    print("       (Requer autenticacao ou acesso ao arquivo ZIP da CVM)")
    return []


def filtrar_noticias_por_empresa(nome_empresa):
    """Retorna notícias que mencionam a empresa em questão."""
    nome_empresa = (nome_empresa or "").strip()
    if not nome_empresa:
        return pd.DataFrame(columns=['titulo', 'link', 'data', 'categoria'])
    try:
        with engine.connect() as conn:
            df = pd.read_sql(
                """
                SELECT titulo, link, data, categoria
                FROM noticias
                WHERE UPPER(titulo) LIKE UPPER(:padrao)
                ORDER BY data DESC NULLS LAST
                LIMIT 10
                """,
                engine,
                params={"padrao": f"%{nome_empresa}%"},
            )
        return df
    except Exception as e:
        print(f"[ERRO] Falha ao filtrar noticias: {e}")
        return pd.DataFrame(columns=['titulo', 'link', 'data', 'categoria'])


def gerar_alerta_investidas(nome_empresa):
    """Gera texto de alerta se houver notícias ou fatos da empresa."""
    noticias = filtrar_noticias_por_empresa(nome_empresa)
    if noticias.empty:
        return None

    alerta = f"Noticias sobre {nome_empresa}:\n"
    for _, row in noticias.iterrows():
        alerta += f"  - {row['titulo']} ({row['categoria']}) — {row['data']}\n"
    return alerta


if __name__ == "__main__":
    criar_tabela_investidas()
    criar_tabela_empresas_interesse()
    print("\n=== Teste de monitoramento ===")
    adicionar_empresa_interesse("Itausa", "17.197.092/0001-91")
    noticias = filtrar_noticias_por_empresa("Itausa")
    print(f"Encontradas {len(noticias)} noticias")
    if not noticias.empty:
        print(noticias.head())
